### ISSUE TITLE
如何获取原始参数

### ISSUE THREAD

**Issue by zuozhehao** [gookit/slog#104]
`slog.PushHandlers(handler...)`

```go
func (n *notify) Handle(record *slog.Record) error {

	return nil
}
```
在record 如何获取`slog.Error` 传入的args

**Comment by inhere** [comment]
handler 这里拿不到了， args 已经被格式化到 record.Message 了

**Comment by zuozhehao** [comment]
> handler 这里拿不到了， args 已经被格式化到 record.Message 了

是否有别的方法可以拿到，便于判断是否需要做通知

**Comment by inhere** [comment]
这种情况应该设置 context data 或者 extra 数据, 使用更方便：

```go
// add log
slog.WithData(slog.M{"notify": true}).Info("some message")

// in handler

func (n *notify) Handle(record *slog.Record) error {
	notify := record.Data["notify"]
	return nil
}

```

**Comment by zuozhehao** [comment]
> 这种情况应该设置 context data 或者 extra 数据, 使用更方便：
> 
> ```go
> // add log
> slog.WithData(slog.M{"notify": true}).Info("some message")
> 
> // in handler
> 
> func (n *notify) Handle(record *slog.Record) error {
> 	notify := record.Data["notify"]
> 	if notify {
> 		// do something ...
> 	}
> 	return nil
> }
> ```
@inhere 
1、那这样就需要在所有地方都加上`.WithData(slog.M{"notify": true})`，
2、对于那些返回自定义`error` 的有附加数据得`map[string]any`，那我还需要把`map[string]any` 转成`slog.M`

需要做以上两个处理才可以。

如果能在record 拿到args,那改动就很小，`slog.Error(err)` 只需在record拿到参数断言判断下就可以做很多事情。

**Comment by inhere** [comment]
是针对 `err error` 场景吗？

**Comment by inhere** [comment]
发了 [v0.5.2](https://github.com/gookit/slog/releases/tag/v0.5.2), logger 新增了选项：

```go
	// BackupArgs backup log input args to Record.Args
	BackupArgs bool
```
