### ISSUE TITLE
能在 golang 1.10 版本下使用吗

### ISSUE THREAD

**Issue by WingDust** [gookit/slog#106]
**System (please complete the following information):**

 - OS: `linux` [e.g. linux, macOS]
 - GO Version: `1.13` [e.g. `1.13`]
 - Pkg Version: `1.1.1` [e.g. `1.1.1`]

**Describe the bug**

**To Reproduce**

```go
// go code
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by inhere** [comment]
：） 应该不行的，用了 `any` 之类的 `1.18+` 才支持
