### ISSUE TITLE
在Console模式下也支持类似withfield功能

### ISSUE THREAD

**Issue by Kinmfer** [gookit/slog#115]
例如zap有zap.String(),zap.Any()等等，在打印一些附带信息的时候会更方便点

**Comment by inhere** [comment]
logger使用时，跟输出模式无关，添加不同handler就输出不同地方。
`logger.WithField()` 始终是可用的。

**Comment by Kinmfer** [comment]
> logger使用时，跟输出模式无关，添加不同handler就输出不同地方。 `logger.WithField()` 始终是可用的。
不过我这样使用了之后确实没有输出field，是我哪里使用方式有问题嘛
![图片](https://github.com/gookit/slog/assets/47661687/2439d89b-01ff-4971-9f7a-863a1b6fd506)
![图片](https://github.com/gookit/slog/assets/47661687/2b04e2a6-e755-4255-bddd-fbf04c48b362)

**Comment by inhere** [comment]
默认模板：

```go
	DefaultTemplate = "[{{datetime}}] [{{channel}}] [{{level}}] [{{caller}}] {{message}} {{data}} {{extra}}\n"
```

新增字段需要改输出模板:

```go
// new field: key => {{key}}
myTemplate := "[{{datetime}}] [{{level}}] {{key}} {{message}} {{data}} {{extra}}\n"

slog.GetFormatter().(*log.TextFormatter).SetTemplate(myTemplate)
```

如果只是想追加一些临时数据，可以用 `WithData()`

**Comment by Kinmfer** [comment]
> **TIP:** 字段是每条日志固定输出的，如果只是想追加一些临时数据，可以用 `WithData()`
> 
> 默认模板：
> 
> ```go
> DefaultTemplate = "[{{datetime}}] [{{channel}}] [{{level}}] [{{caller}}] {{message}} {{data}} {{extra}}\n"
> ```
> 
> 新增字段需要改输出模板:
> 
> ```go
> // new field: key => {{key}}
> myTemplate := "[{{datetime}}] [{{level}}] {{key}} {{message}} {{data}} {{extra}}\n"
> 
> slog.GetFormatter().(*log.TextFormatter).SetTemplate(myTemplate)
> ```
好的 withdata是可以的，不过文档里可能需要修改下
![图片](https://github.com/gookit/slog/assets/47661687/11196e9b-6437-41af-b06e-66500f6cd34f)
1.slog.NewWithHandlers()需要改成slog.NewWithHandlers(h)
2.handler没有GetFormatter方法,slog是有的
![图片](https://github.com/gookit/slog/assets/47661687/eff2f919-1b63-403b-b0e0-4a6226693d7c)

**Comment by inhere** [comment]
handler 一般都包装了 `Formattable interface`:

```go

// Formattable interface
type Formattable interface {
	// Formatter get the log formatter
	Formatter() Formatter
	// SetFormatter set the log formatter
	SetFormatter(Formatter)
}
```

😂 文档上写错误了。该是 `h.Formatter()`, 文档上有很多功能点可能没写全，可以跳转进去看源码或者test😂

**Comment by Kinmfer** [comment]
> 

好嘞好嘞，感谢大佬，很喜欢这个日志库，不仅简洁而且高效
