### ISSUE TITLE
use type alias instead of uint8 for CallerFlag

### ISSUE THREAD

**Issue by ShyunnY** [gookit/slog#154]
I am a beginner in gookit/slog. When I was deeply customizing `*slog.Logger`, I was confused about the `uint8` of `CallerFlag`, and I didn't seem to see any explanation in the documentation(Maybe many people will have this doubt). This requires me to search the context to understand its optional values.

So I think we can define a type alias, which will help us quickly understand its role from the context.

> I'd be happy to fix him if I could.

**Comment by inhere** [comment]
Welcome to submit PR.

Their definition is here：

https://github.com/gookit/slog/blob/3fd68fc0c5754d43687ba862838d299f464b90db/common.go#L99-L127
