### ISSUE TITLE
Trying to understand slog log levels

### ISSUE THREAD

**Issue by hackquest-grid** [gookit/slog#17]
It looks to me that levels are inverted compared to the usual things, for example :
- setting DebugLevel will print only Debug message, not errors or warning or info
- setting ErrorLevel will print Trace,Debug,Info,Warn and Error

That's usually the opposite, when setting Error level, we only want errors. If setting Info we want errors, warning and info messages, an so on.

Is there something I didn't understand ?

**Comment by inhere** [comment]
sorry, My check is wrong :(

**Comment by hackquest-grid** [comment]
> sorry, My check is wrong :(

No problem, the important is that is fixed ;-)
