### ISSUE TITLE
How to compress the (old) log file after rotation?

### ISSUE THREAD

**Issue by iredmail** [gookit/slog#55]
Dear developers,

- How can i configure slog to compress the (old) log file after rotation?
- 如何在 rotate 之后压缩旧 log 文件？

Thanks for helping. :)

**Comment by inhere** [comment]
1. 设置一个稍大于rotate time 的后台定时器，定时处理
2. 我可以添加一个 hook func，在rotate file完成后触发

**Comment by iredmail** [comment]
rotate 后压缩，这操作非常普遍，建议将它作为一个内置功能，不需要调用者额外处理。优先用 gzip（速度快，虽然压缩比不如 bzip2 等，但较为平衡）。

**Comment by inhere** [comment]
可以的，下个小版本我加下

**Comment by iredmail** [comment]
太赞了。:)

**Comment by inhere** [comment]
已经实现，发布了 `v0.3.2`

**Comment by iredmail** [comment]
非常感谢。:)
