### ISSUE TITLE
如何禁用console日志输出？

### ISSUE THREAD

**Issue by fzdwx** [gookit/slog#75]

**Comment by inhere** [comment]
测试时可以的：

> 也可以设置更低点 `slog.SetLogLevel(slog.Level(0))`

![image](https://user-images.githubusercontent.com/5302062/190296756-91cfe0b0-75d9-4fd6-a454-2e38f2b7b1bd.png)

**Comment by fzdwx** [comment]
ok，我的log是写在 init 里面的，然后 set log 比这个 init 执行迟一点。
