### ISSUE TITLE
被maxSize切割过的文件无法被RotateTime的压缩

### ISSUE THREAD

**Issue by pya789** [gookit/slog#89]
第一步：1月31号触发maxSize切割文件并压缩
![1](https://user-images.githubusercontent.com/12424245/215714744-9cab5041-79a7-45bf-9e44-bb6550d1fc35.png)
第二部：更改系统时间为2月1号，并触发RotateTime RotateTime只压缩了当前读写的文件并且时间为2月1号，里面的内容也不对
![2](https://user-images.githubusercontent.com/12424245/215715398-6bca2aad-d116-4141-b721-296c2316261d.png)
![3](https://user-images.githubusercontent.com/12424245/215715819-82b3e98a-d60b-40ef-bd7b-7f773535a62d.png)

**Comment by inhere** [comment]
更新到新版本试试看

**Comment by pya789** [comment]
> 更新到新版本试试看

好的 谢谢
